# Deprecated routes: /info and /health are moving to /internal/info and internal/health respectively.
monitor.info:
    path: /info
    methods: [GET]
    defaults:
        _controller: OpenConext\MonitorBundle\Controller\InfoController

monitor.health:
    path: /health
    methods: [GET]
    defaults:
        _controller: OpenConext\MonitorBundle\Controller\HealthController

monitor.internal_info:
    path: /internal/info
    methods: [GET]
    defaults:
        _controller: OpenConext\MonitorBundle\Controller\InfoController

monitor.internal_health:
    path: /internal/health
    methods: [GET]
    defaults:
        _controller: OpenConext\MonitorBundle\Controller\HealthController
