# OS: Linux; Symfony: upcoming (still unreleased) version; PHP: latest stable
name: "Tests - Upcoming Symfony version (allowed to fail !)"

on: ["pull_request"]

env:
  fail-fast: true

jobs:
  tests:
    runs-on: 'ubuntu-latest'
    continue-on-error: true
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Install PHP with extensions'
        uses: shivammathur/setup-php@2.22.0
        with:
          coverage: none
          php-version: '8.2'
          tools: composer:v2
          extensions: mbstring
          ini-values: date.timezone=UTC

      - name: 'Install project dependencies'
        env:
          SYMFONY_REQUIRE: '6.4.x@dev'
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require --no-progress --no-scripts --no-plugins symfony/flex
          composer config minimum-stability dev
          composer config prefer-stable false
          composer update --no-interaction --optimize-autoloader
          composer require symfony/phpunit-bridge

      - name: 'Run tests'
        env:
          SYMFONY_DEPRECATIONS_HELPER: 'weak'
          #SYMFONY_DEPRECATIONS_HELPER: 'max[indirect]=9999&max[direct]=0&max[self]=9999'
        run: vendor/bin/phpunit -v || exit 0
